{{- $secretName := printf "%s-config" (include "mongodb.fullname" .) }}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $random := "" }}
{{- if $existing }}
  {{- $random = index $existing.data "mongod_key" }}
{{- else }}
  {{- $random = randBytes 756 | b64enc }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
type: Opaque
data:
  mongod_key: {{ $random }}
{{ (.Files.Glob "files/mongod.conf").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ required "auth.rootPassword must be set" .Values.auth.rootPassword | quote }}
