apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
      protocol: TCP
  selector:
    {{- include "helper.selectorLabels" . | nindent 4 }}
