apiVersion: v1
kind: Service
metadata:
  name: {{ include "helper.fullname" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "helper.selectorLabels" . | nindent 4 }}
  ports:
{{- if ((.Values.global).ingress).enabled }}
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
{{- else }}
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
{{- end }}
