apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.adminUser | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ required "adminPassword must be set" .Values.adminPassword | quote }}
  KEYCLOAK_ADMIN: {{ .Values.adminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ required "adminPassword must be set" .Values.adminPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-pg
  labels:
    {{- include "helper.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.username | quote }}
  POSTGRES_PASSWORD: {{ required "postgresql.password must be set" .Values.postgresql.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
